DELETE FROM LICENSES;

INSERT INTO LICENSES(ID, NAME) VALUES ('A', 'Basic');
INSERT INTO LICENSES(ID, NAME) VALUES ('B', 'Medium');
INSERT INTO LICENSES(ID, NAME) VALUES ('C', 'Professional');
INSERT INTO LICENSES(ID, NAME) VALUES ('D', 'Guru');
INSERT INTO LICENSES(ID, NAME) VALUES ('E', 'NASA');
